package heiko

import java.util.*

val positiveStickers = arrayOf(
    "CAADAgADnAIAAj-VzAovQnDNQQe33QI", "CAADAgADnwEAAgeGFQfRYJU4HtbsvAI",
    "CAADAgADuAUAAvoLtghew_BTab-Q-QI", "CAADAgADtQUAAmMr4gm433nFpTkpEAI", "CAADAgADBwIAAtzyqwdVSve97Ve_kQI",
    "CAADAgADewUAAhhC7ggL5p5h3oDTAwI", "CAADAgADjAIAAj-VzArhgivUMNJrhgI", "CAADAgAD6QAEOKAKSndrbn6hA3EC",
    "CAADAgADfQMAAsSraAvoUE-v_dODPwI", "CAADAgADyAUAAvoLtgi1ezx5lIjuZwI"
)
val unknownStickers = arrayOf(
    "CAADAgAD3wEAAjZ2IA4lakrBbQW2kwI", "CAADAgADIAYAAhhC7ggr3IgQ7CWJQgI",
    "CAADAgADbAUAAhhC7gjcgXuEy0jstgI", "CAADAgADawUAAhhC7gi-w6EkmXJ3sgI", "CAADAgADQwMAAsSraAvAEH7acBV_uAI",
    "CAADAgAD0AUAAvoLtgheMMFYmtIxMQI", "CAADAgADzwIAAj-VzAqZJmrw1nWAUAI", "CAADAgADfAUAAhhC7gjEYV0FBA_xjgI"
)
val negativeStickers = arrayOf(
    "CAADAgADIAADyIsGAAGwI-I5pMSEdQI", "CAADAgADLwIAArrAlQXCB-MwsRsKUAI",
    "CAADAgAD6AMAAvJ-ggyV1koZSeQd7QI", "CAADAgADdQIAAsSraAthqwkz4CCMGwI", "CAADAgADKwIAAj-VzAq8_jVvbB-ZgQI",
    "CAADAgADTAUAAmMr4glGKjnwtWFTIAI", "CAADAgAD6wEAAiCBFQABCQn4d2vDOrcC", "CAADAgAD5QADNnYgDr7EklL1F-d-Ag",
    "CAADAgADuQEAAgeGFQcm74jOQU-L8wI"
)

val fireworkStickers = arrayOf(
    "CAACAgIAAxkBAAID-F_th3737x8itH27DInIcMbJ_oDyAALlAQACFkJrCm6aK1JKYMuoHgQ",
    "CAACAgIAAxkBAAID-l_th5DbRbIvEkLtk9uYcBlr4vaOAALmAQACFkJrCkbP8M3aTyDhHgQ",
    "CAACAgIAAxkBAAID_F_th5KiS848eWDU5_t3LVqFUDGkAALoAQACFkJrCgtMrejShZ9SHgQ",
    "CAACAgIAAxkBAAID_l_th5ldvjPdVMX_zMW_Ee7lAUaBAALeAQACFkJrCnwEvNlWWBpwHgQ",
    "CAACAgIAAxkBAAIEAAFf7YecV-FpfeSXV66zrW01E6RgHgAC3wEAAhZCawr990u6o9iWvh4E",
    "CAACAgIAAxkBAAIEBF_th6Zps2KlxG2SrUXnGIUGD9rQAALjAQACFkJrCkthY0o6Q02yHgQ",
    "CAACAgIAAxkBAAIEBl_th7DMzw548NL9cSoQS63NZy0BAALtAQACFkJrCumyRSKn9g9THgQ",
    "CAACAgIAAxkBAAIECF_th7f5uAQp9K-RHUDJTWc0PypZAALbAQACFkJrCkHoj1RHJXBAHgQ",
    "CAACAgIAAxkBAAIECl_th7qoPuSfiqFbszLClXMoYRGDAALzAQACFkJrCv1U0WZtYEgNHgQ",
    "CAACAgIAAxkBAAIEDF_th75RT-u0mYWFCpJ88ufUAnLKAAL1AQACFkJrCkfk4mTkrqAmHgQ",
    "CAACAgIAAxkBAAIEDl_th8CtrzoWgv7jpSKICslJXjSwAAL2AQACFkJrCpyYtVJzRdKnHgQ",
    "CAACAgIAAxkBAAIEEl_tiJ12MlJlMEvODSzyZwZTCwXLAAIKAQACzhp2Cz1llF37DOBkHgQ",
    "CAACAgIAAxkBAAIEFF_tiKJwXSwGUGFWHDXwFbupGjE4AAILAQACzhp2CztHzmvwcRGgHgQ",
    "CAACAgIAAxkBAAIEGF_tiN4ulFraTalaRpSivcBqRyS2AAKqAQACMNSdEQ-7EDafnMwvHgQ",
    "CAACAgIAAxkBAAIEGl_tiO-mEWkevZTI-E1uxtVJwUrhAAK8AQACMNSdESIsgSPxGX7EHgQ",
    "CAACAgIAAxkBAAIEHl_tiS2E207XaCE1x5izMWlqPJQnAALvAQACwZGyJOgkZ-9ryKq3HgQ",
    "CAACAgIAAxkBAAIEIF_tiTaZqwio-_jwj4U8UNFm4fb0AAKbAAOvxlEaEVlpqld5nqEeBA",
    "CAACAgIAAxkBAAIEIl_tiUEbUuLOeormmplGL72GDYliAAKZAAOvxlEaBeAdCalE410eBA",
    "CAACAgIAAxkBAAIEJF_tiU005uoFfITsEyE4QEm6m-cOAAKXAAOvxlEa9Ih0MPcQDwQeBA"
)

private val random = Random()
fun <T> Array<T>.random() = get(random.nextInt(size))
